### PR TITLE
fix asyncio errors

### PR DESCRIPTION
**Pull request by void0x**

### CODE REVIEW

**Comment by firmianay** [comment]
为什么要改成异步呢，我没有测试过，有什么明显的好处？

**Comment by void0x** [comment]
Your requirements.txt doesn't list the versions of the libraries.

The latest version of python-telegram-bot is downloaded, it has become asynchronous, and now your old code throws an error. So I fixed it to make everything work. I had to add asynchrony.

**Comment by firmianay** [comment]
在线求用telegram的师傅帮忙测试一下

**Comment by void0x** [comment]
image
For this, I made changes so that posting to telegram with the new version of python-telegram-bot would work for me. Here is a screenshot from my channel, this feed is formed with yarb.

**Comment by firmianay** [comment]
ok, thanks

**Comment by void0x** [comment]
Maybe freeze requirements.py (with versions)?

Otherwise, sooner or later it will break again, because. with the current one, the latest versions of libraries are downloaded, in which they can change something.

**Comment by firmianay** [comment]
I prefer to keep the latest version, and when there is a problem, it can be found and fixed in time

**Comment by firmianay** [comment]
@void0x Hello! The code submitted this time may have caused problems in other bots. Can you fix it?  #20

**Comment by void0x** [comment]
@firmianay Hi! Yes, I'll take a look.

**Pull request merged**
